"""Photo router with cover assignment after flush."""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

# These imports assume the surrounding application provides the expected models
# and dependency wiring. They are kept relative so the router can be integrated
# without modification once the corresponding modules are available.
from ..dependencies import get_db  # type: ignore
from ..models import Album, Photo, PhotoCreate  # type: ignore

router = APIRouter(prefix="/albums", tags=["photos"])


@router.post("/{album_id}/photos", response_model=Photo)
async def create_photo(
    album_id: int, payload: PhotoCreate, db: AsyncSession = Depends(get_db)
) -> Photo:
    """Create a photo and assign it as the album cover if requested.

    The database flush after adding the new photo ensures the autogenerated ID
    is available before assigning it to ``album.cover_photo_id``.
    """
    album = await db.get(Album, album_id)
    if not album:
        raise HTTPException(status_code=404, detail="Album not found")

    photo = Photo(**payload.model_dump(), album_id=album_id)
    db.add(photo)
    await db.flush()

    if payload.set_as_cover:
        album.cover_photo_id = photo.id

    await db.commit()
    await db.refresh(photo)
    return photo
